#pragma once

void TestGridUiaPatternSupportsBoundedOffscreenGetItem();
void TestGridUiaPatternStopsWhenCellReadReplacesItsControl();
void TestGridUiaPatternStopsWhenCellReadShrinksItsModel();
void TestGridUiaPatternRetriesSupersededSameAddressCapture();
void TestGridUiaPatternStopsWhenCellReadNotifiesSameModel();
void TestGridUiaPatternStopsPointHitsAfterModelReplacement();
void TestGridUiaPatternInvalidatesProvidersAfterSameAddressModelAssignment();
void TestGridUiaPatternPreservesAssignmentDuringCachedCellCreation();
void TestGridUiaPatternContainsModelExceptionsAtTheProviderBoundary();
