# Overlay triplets that pin vcpkg to the Visual Studio installation and MSVC toolset MSBuild compiles DxUi with. Left alone,
# vcpkg builds with the newest toolset it finds. That can be one with no compiler for a target (a side-by-side toolset lacking
# the x64-hosted ARM64 compiler), and for compiled libraries it is a toolset newer than the one that links them. The overlay is
# the stock triplet's text, copied, plus two pins; vcpkg takes the overlay in place of the triplet of the same name.
Set-StrictMode -Version Latest

function ConvertTo-CMakeQuotedArgument([string] $Value) {
    # In a CMake quoted argument a backslash, a double quote and a dollar sign are special; every other character is literal.
    return '"' + [regex]::Replace($Value, '[\\"$]', '\$&') + '"'
}

function Get-DxUiVcpkgOverlayTripletText {
    <# The overlay triplet's text: the stock text unchanged, then the pins. It keeps the stock text's line endings (the stock
       arm64-windows.cmake has CRLF and x64-windows.cmake LF), so the copy stays one consistent file. Pure: no I/O. #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][AllowEmptyString()][string] $StockText,
        [Parameter(Mandatory)][ValidateNotNullOrEmpty()][string] $Installation,
        [Parameter(Mandatory)][ValidatePattern('^[0-9]+\.[0-9]+$')][string] $ToolsetVersion
    )
    $newline = if ($StockText.Contains("`r`n")) { "`r`n" } else { "`n" }
    $text = $StockText
    if ($text.Length -and -not $text.EndsWith("`n", [StringComparison]::Ordinal)) { $text += $newline }
    if ($text.Length) { $text += $newline }
    $pins = @(
        '# DxUi: build with the Visual Studio installation and default MSVC toolset MSBuild uses (generated by vcpkg-install.ps1; do not edit).',
        "set(VCPKG_VISUAL_STUDIO_PATH $(ConvertTo-CMakeQuotedArgument $Installation))",
        "set(VCPKG_PLATFORM_TOOLSET_VERSION $(ConvertTo-CMakeQuotedArgument $ToolsetVersion))")
    return $text + (($pins -join $newline) + $newline)
}

function Update-DxUiVcpkgOverlayTriplet {
    <# Writes <OutputDirectory>/<name>.cmake, the overlay of the triplet at StockTripletPath (normally the pinned vcpkg
       checkout's triplets/<name>.cmake; a consumer's own overlay triplet works as well) pinned to the toolset that
       Get-DxUiDefaultToolset returned, and only when the file's bytes would change, so an unchanged restore leaves its timestamp
       alone. Changing the triplet changes vcpkg's package ABI hash, so the first restore after a change rebuilds the packages.
       Returns Triplet, Directory (what --overlay-triplets takes), Path and Changed. #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory)][string] $StockTripletPath,
        [Parameter(Mandatory)] $Toolset,
        [Parameter(Mandatory)][string] $OutputDirectory
    )
    # Relative paths mean the caller's PowerShell location, which .NET file calls do not know.
    $StockTripletPath = $PSCmdlet.GetUnresolvedProviderPathFromPSPath($StockTripletPath)
    $OutputDirectory = $PSCmdlet.GetUnresolvedProviderPathFromPSPath($OutputDirectory)
    if (-not [IO.File]::Exists($StockTripletPath)) {
        throw "The triplet to pin does not exist: $StockTripletPath. The vcpkg checkout does not have it; check the triplet name and the checkout."
    }
    $name = [IO.Path]::GetFileName($StockTripletPath)
    $text = Get-DxUiVcpkgOverlayTripletText -StockText ([IO.File]::ReadAllText($StockTripletPath)) -Installation $Toolset.Installation -ToolsetVersion $Toolset.MajorMinor
    $bytes = [Text.UTF8Encoding]::new($false).GetBytes($text)
    $path = Join-Path $OutputDirectory $name
    $changed = -not ([IO.File]::Exists($path) -and [Convert]::ToBase64String([IO.File]::ReadAllBytes($path)) -ceq [Convert]::ToBase64String($bytes))
    if ($changed) {
        [void][IO.Directory]::CreateDirectory($OutputDirectory)
        [IO.File]::WriteAllBytes($path, $bytes)
    }
    return [pscustomobject]@{ Triplet = [IO.Path]::GetFileNameWithoutExtension($name); Directory = $OutputDirectory; Path = $path; Changed = $changed }
}

Export-ModuleMember -Function Get-DxUiVcpkgOverlayTripletText, Update-DxUiVcpkgOverlayTriplet
